edition = "2021"
style_edition = "2021"
unstable_features = false

hard_tabs = false
tab_spaces = 4
max_width = 100
newline_style = "Unix"

imports_granularity = "Crate"
group_imports = "StdExternalCrate"
reorder_imports = true

trailing_comma = "Always"
use_field_init_shorthand = true
format_code_in_doc_comments = true
wrap_comments = false
comment_width = 100

error_on_line_overflow = true
error_on_unformatted = true

reorder_impl_items = false
spaces_around_ranges = false