# Disable unstable features for CI stability
unstable_features = false

# Basic formatting rules
hard_tabs = true
max_width = 100
reorder_imports = true
newline_style = "Unix"
trailing_comma = "Always"

# Explicitly disable nightly-only features
wrap_comments = false
imports_granularity = "Preserve"