# Enable unstable features
unstable_features = true

# Preserve current preferences
hard_tabs = true
max_width = 100
reorder_imports = true

# Add settings to fix the issues in your diffs
newline_style = "Unix"
trailing_comma = "Always"