# Core formatting rules
unstable_features = false
hard_tabs = false  # Changed to spaces for consistency
max_width = 100
reorder_imports = true
newline_style = "Unix"
trailing_comma = "Always"

# Disabled features
wrap_comments = false
imports_granularity = "Preserve"

# Substrate-specific preferences
group_imports = "StdExternalCrate"
format_code_in_doc_comments = true