[build]
rustdocflags = [
	"-Dwarnings",
	"-Arustdoc::redundant_explicit_links",
]

[env]
CC_x86_64_unknown_linux_musl = { value = ".cargo/musl-gcc", force = true, relative = true }
CXX_x86_64_unknown_linux_musl = { value = ".cargo/musl-g++", force = true, relative = true }
CARGO_WORKSPACE_ROOT_DIR = { value = "", relative = true }
SQLX_OFFLINE = "true"

[net]
retry = 5
git-fetch-with-cli = false # Explicitly disabled